rabbitStew:
  image: node
  working_dir: /code
  volumes:
    - .:/code
  links:
    - rabbit
  environment:
    RABBIT_URL: 'amqp://rabbit'
rabbit:
  image: andrewkeig/rabbitmq-mqtt-enabled
  ports:
   - "15672:15672"
   - "5672:5672"
   - "1883:1883"